In [5]:
import numpy as np

a = np.array([[1,2,3,4],[4,5,6,7]])

In [7]:
a

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

<b>Dimensions Of the array</b>

In [9]:
a.ndim

2

<b>Shape Of the array</b>

In [14]:
print( "Shape of the array = " , a.shape)
print( 'Number of rows = ' , a.shape[0])
print( 'Number of columns = ' , a.shape[1])

Shape of the array =  (2, 4)
Number of rows =  2
Number of columns =  4


<b>Initialising Array</b>

In [59]:
rows = 3
cols = 5

a = np.ones( (rows,cols) , dtype='int8' )
a.dtype     # data type of the array passing dtype is optional

a = np.zeros( (rows,cols) ,dtype='complex' )
a.dtype

a = np.arange(10,20,2,dtype='int64')    # start , end ,stepsize , dtype
a

array([10, 12, 14, 16, 18])

<b>Generating n numbers between given two numbers</b>

In [69]:
a = np.linspace( 0.01 , 0.02  , 10 )  # start , end  , number of numbers 
a  

b = np.linspace( 1 , 2 , 5 , dtype='float128' )
b

array([1.  , 1.25, 1.5 , 1.75, 2.  ], dtype=float128)

<b>Import Methods for array manipulation</b>

In [98]:
a = np.ones((3,4))
print( 'Array a = \n' , a)

# Reshape the array
b = a.reshape((6,2))
print('Array b = \n',b)
# Flatten the array
c = a.ravel()
print('Array c = \n',c)

a.reshape((4,3))

Array a = 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Array b = 
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Array c = 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

<b>Important methods to extract info</b>

In [140]:
a = np.arange( 1 , 13 )  
a = a.reshape((3,4))
print('Array A = \n',a)

print('Min = ' + str(a.min()))
print('Max = ' + str(a.max()))
print('Sum of the array elements = ' + str(a.sum()))
print('Standard Deviation  = ' + str(np.std(a)))
print('Mean = ' + str(np.mean(a)))
print('Square root : \n',np.sqrt(a))


Array A = 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Min = 1
Max = 12
Sum of the array elements = 78
Standard Deviation  = 3.452052529534663
Mean = 6.5
Square root : 
 [[1.         1.41421356 1.73205081 2.        ]
 [2.23606798 2.44948974 2.64575131 2.82842712]
 [3.         3.16227766 3.31662479 3.46410162]]


<b>Rowwise and ColumnWise Sum . Remember that axis=0 corresponds to column and axis=1 corresponds to row</b>

In [128]:
a = np.arange(1,21)
a = a.reshape((4,5))

print(a)

colsum = a.sum(axis=0)
print('\nColumn Wise sum = ' + str(colsum))

rowsum = a.sum(axis=1)
print('Row Wise sum = ' + str(rowsum))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

Column Wise sum = [34 38 42 46 50]
Row Wise sum = [15 40 65 90]


<b>3-d Array </b>

In [134]:
a = np.array(
    [
        [[1,2],
        [3,4]],
        
        [[5,6],
        [7,8]]
    ]
)
a.sum(axis=0)
a.sum(axis=1)
a.sum(axis=2)


array([[ 3,  7],
       [11, 15]])

<b>Some Numerical Stuff</b>

In [156]:
a = np.arange(1,21)
a = a.reshape(5,4)
b = np.ones((5,4))

c = a + b
c

d = a * b
d

e = a / b
e

matrix_product = a.dot(b.reshape(4,5))
matrix_product

array([[10., 10., 10., 10., 10.],
       [26., 26., 26., 26., 26.],
       [42., 42., 42., 42., 42.],
       [58., 58., 58., 58., 58.],
       [74., 74., 74., 74., 74.]])